<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dashboard extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->authclass->check_isvalidated(base_url());
        $this->load->model('Produk_model');
        $this->load->model('Barang_model');
        // $this->load->model('Users_model');
        // $this->load->model('Transaksi_model');
    }

    public function index()
    {
        $row = $this->Produk_model->get_max("transaksi_pemesanan");
        $row2 = $this->Produk_model->get_max("transaksi_penjualan");
        $row3 = $this->Produk_model->get_sum("tanggal_transaksi","jml_pembayaran","transaksi_pemesanan");
        $row4 = $this->Produk_model->get_sum("tanggal_transaksi","jml_pembayaran","transaksi_penjualan");
        $row5 = $this->Produk_model->get_sum("tanggal","nominal","transaksi_pengeluaran");
        // print_r($row3->);exit();
        $data = array(
            'title' => 'Dashboard',
            'ttlpemesanan' => $row,
            'ttlpenjualan' => $row2,
            'pemasukkan' => ($row3->jml_pembayaran+$row4->jml_pembayaran),
            'pengeluaran' => $row5->nominal,
        );

        $this->template->load('template','dashboard', $data);
    }

    public function json() {
        header('Content-Type: application/json');
        echo $this->Barang_model->json();
    }
    
}

/* End of file Kategori.php */
/* Location: ./application/controllers/Kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-02-07 01:38:10 */
/* http://harviacode.com */