<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Status_pemesanan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Transaksi_pemesanan_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }    

    public function index()
    {
        $data = $this->Transaksi_pemesanan_model->get_all_p2();
        $bp = $this->Transaksi_pemesanan_model->get_pesananditerima();
        $sd = $this->Transaksi_pemesanan_model->get_pesanandiproses();
        $ps = $this->Transaksi_pemesanan_model->get_pesananselesai();
        // $bp = $this->Transaksi_pemesanan_model->get_pesanandikirim();
        $data = array(
            'title'=>'Status Pemesanan',
            'data'=>$data,
            'bp'=>$bp,
            'sd'=>$sd,
            'ps'=>$ps,
        );
        $this->template->load('template','transaksi_pemesanan/status_pemesanan_list', $data);
    } 

    public function update_action($status,$id_transaksi_pemesanan) 
    {
        switch ($status) {
            case 1:
                $status = "pesanan diterima";
                break;
            case 2:
                $status = "sudah dipotong";
                break;
            case 3:
                $status = "dijahit";
                break;
            case 4:
                $status = "finishing";
                break;
            case 5:
                $status = "pesanan selesai";
                break;
        }

        if (!empty($id_transaksi_pemesanan) && !empty($status)) {
            $data = array('status' => $status,);

            $this->Transaksi_pemesanan_model->update($id_transaksi_pemesanan, $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('status_pemesanan'));
        }
    }

}

/* End of file Transaksi_pemesanan.php */
/* Location: ./application/controllers/Transaksi_pemesanan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-24 08:01:38 */
/* http://harviacode.com */