<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barang_masuk_model extends CI_Model
{

    public $table = 'barang_masuk';
    public $id = 'idbrgmasuk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idbrgmasuk,tanggal,id_barang,sku,nama_barang,jenis_barang,penerima,pemasok,tandaterima,jumlah,unit,harga_beli');
        $this->datatables->from('view_barang_masuk');
        //add this line for join
        //$this->datatables->join('table2', 'barang_masuk.field = table2.field');
        $this->datatables->add_column('ttd', '<img onclick="myImg('."'$1'".')" id="$1" src="'.base_url().'filw/$1" style="width:100%;max-width:300px">', 'tandaterima');
        $this->datatables->add_column('action', anchor(site_url('barang_masuk/read/$1'),'Read')." | ".anchor(site_url('barang_masuk/update/$1'),'Update')." | ".anchor(site_url('barang_masuk/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'idbrgmasuk');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idbrgmasuk', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('id_barang', $q);
	$this->db->or_like('penerima', $q);
	$this->db->or_like('pemasok', $q);
	$this->db->or_like('tandaterima', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('harga_beli', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idbrgmasuk', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('id_barang', $q);
	$this->db->or_like('penerima', $q);
	$this->db->or_like('pemasok', $q);
	$this->db->or_like('tandaterima', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('harga_beli', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Barang_masuk_model.php */
/* Location: ./application/models/Barang_masuk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-19 17:14:20 */
/* http://harviacode.com */