<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Produk_model extends CI_Model
{

    public $table = 'produk';
    public $view = 'view_barang';
    public $id = 'id_produk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_max($table)
    {
        $this->db->where('DATE(tanggal_transaksi) = DATE(NOW())');
        return $this->db->get($table)->num_rows();
    }
    function get_sum($tgl,$field,$table)
    {
        $this->db->select_sum($field);
        $this->db->where('MONTH('.$tgl.') = MONTH(CURRENT_DATE()) AND YEAR('.$tgl.') = YEAR(CURRENT_DATE())');
        return $this->db->get($table)->row();
    }

    // datatables
    function json() {
        $this->datatables->select('id_barang,sku,nama_barang,jenis_barang,kategori,ukuran,varian,nama_varian,stok,unit,harga_jual');
        $this->datatables->from($this->view);
        // $this->datatables->where("stok", "0");
        //add this line for join
        //$this->datatables->join('table2', 'barang.field = table2.field');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
           // get all
    function get_all5($table)
    {
        // $this->db->order_by($this->id, $this->order);
        return $this->db->get($table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_link($id)
    {
        $this->db->where('id_kategori', $id);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_produk', $q);
	$this->db->or_like('nama_produk', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('harga_sewa', $q);
	$this->db->or_like('detail_produk', $q);
	$this->db->or_like('gambar_produk', $q);
	$this->db->or_like('stok_produk', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_produk', $q);
	$this->db->or_like('nama_produk', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('harga_sewa', $q);
	$this->db->or_like('detail_produk', $q);
	$this->db->or_like('gambar_produk', $q);
	$this->db->or_like('stok_produk', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }
    function insertt($tr,$data)
    {
        $this->db->insert($tr, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Produk_model.php */
/* Location: ./application/models/Produk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-16 15:48:46 */
/* http://harviacode.com */