<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Transaksi_penjualan_model extends CI_Model
{

    public $table = 'transaksi_penjualan';
    public $table2 = 'transaksi_penjualan_detail';
    public $id = 'id_transaksi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('transaksi_penjualan.id_transaksi,tanggal_transaksi,potongan,jumlah_potongan,jml_pembayaran,total,jenis_pembayaran, pelanggan.nama_pelanggan');
        $this->datatables->from('transaksi_penjualan');
        //add this line for join
        $this->datatables->join('pelanggan', 'transaksi_penjualan.id_pelanggan = pelanggan.id_pelanggan');
        $this->datatables->add_column('action', anchor(site_url('transaksi_penjualan/read/$1'),'Read')." | ".anchor(site_url('transaksi_penjualan/update/$1'),'Update')." | ".anchor(site_url('transaksi_penjualan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_transaksi');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_by_id($id){
        $this->db->select('id_transaksi,tanggal_transaksi,transaksi_penjualan.id_pelanggan,potongan,jumlah_potongan,jenis_pembayaran,jml_pembayaran,total,pelanggan.nama_pelanggan');
        $this->db->from($this->table);
        $this->db->join('pelanggan', 'transaksi_penjualan.id_pelanggan = pelanggan.id_pelanggan');
        $this->db->where($this->id, $id);

        return $this->db->get()->row();
    }

    function get_by_detail($id)
    {
        $this->db->select('id_transaksi_penjualan,transaksi_penjualan_detail.id_barang,qty,transaksi_penjualan_detail.harga_jual,subtotal,barang.nama_barang,unit');
        $this->db->from($this->table2);
        $this->db->join('barang', 'barang.id_barang = transaksi_penjualan_detail.id_barang');
        $this->db->where('id_transaksi_penjualan', $id);
        return $this->db->get()->result();
    }
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_transaksi', $q);
	$this->db->or_like('tanggal_transaksi', $q);
	$this->db->or_like('id_pelanggan', $q);
	$this->db->or_like('potongan', $q);
	$this->db->or_like('jumlah_potongan', $q);
	$this->db->or_like('jml_pembayaran', $q);
	$this->db->or_like('total', $q);
	$this->db->or_like('jenis_pembayaran', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_transaksi', $q);
	$this->db->or_like('tanggal_transaksi', $q);
	$this->db->or_like('id_pelanggan', $q);
	$this->db->or_like('potongan', $q);
	$this->db->or_like('jumlah_potongan', $q);
	$this->db->or_like('jml_pembayaran', $q);
	$this->db->or_like('total', $q);
	$this->db->or_like('jenis_pembayaran', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // insert data
    function insert2($data)
    {
        $this->db->insert($this->table2, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function get_max()
    {
        $this->db->select_max($this->id);
        return $this->db->get($this->table)->row();
    }
}

/* End of file Transaksi_penjualan_model.php */
/* Location: ./application/models/Transaksi_penjualan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-21 05:05:26 */
/* http://harviacode.com */